server:
  port: 8080
  servlet:
    context-path: /kafka-service

spring:
  application:
    name: kafka-service
  kafka:
    client-id: kafka-service-client-id
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      properties:
        spring:
          json:
            trusted.packages: "br.com.guilhermemilagre.*"
      group-id: kafka-service-group-id
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 10
      enable-auto-commit: false
    listener:
      concurrency: 10

application:
  kafka:
    listener:
      enable: true
    topics:
      notification: ECOMMERCE_NEW_TOPIC
      history: ECOMMERCE_HISTORY


